version: '2'

services:

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '8082:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: npm start
